on: push
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    environment: dev vps vanchenkin.ru
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: vanchenkin/printifai:front-latest
          build-args: |
            "NEXT_PUBLIC_BACK_HOST=https://printifai.ru/api"
